const questions = [
    {
        question: 'According to Master Yoda, how many Sith are always out there ',
        1: { answer: 4, check: 'false' },
        2: { answer: 3, check: 'false' },
        3: { answer: 1, check: 'false' },
        4: { answer: 2, check: 'true' },
    },
    {
        question: 'What happened to Anakin Skywalker during the battle with Count Dooku?',
        1: { answer: 'He lost his left leg', check: 'false' },
        2: { answer: 'He lost his right arm', check: 'true' },
        3: { answer: 'He lost his right leg', check: 'false' },
        4: { answer: 'He lost', check: 'false' },
    },
    {
        question: 'How did Princess Leia get her title of royalty?',
        1: { answer: 'She is the adopted daughter of Bail Organa and Queen Breha', check: 'true' },
        2: { answer: 'Her sharp aim with a blaster', check: 'false' },
        3: { answer: 'A mocking nickname from Han Solo', check: 'false' },
        4: { answer: 'She is the daughter of Queen Katrina of the Geonosians', check: 'false' },
    },
    {
        question: 'Who destroyed the Droid Control Ship when they accidentally activated a Naboo Fighter’s Autopilot?',
        1: { answer: 'Biggs Darklighter', check: 'false' },
        2: { answer: 'Anakin Skywalker', check: 'true' },
        3: { answer: 'Obi Wan Kenobi', check: 'false' },
        4: { answer: 'Jar Jar Binks', check: 'false' },
    },
    {
        question: 'Where does Yoda live when he first trains Luke Skywalker?',
        1: { answer: 'Tatooine', check: 'false' },
        2: { answer: 'Dagobah', check: 'true' },
        3: { answer: 'Hoth', check: 'false' },
        4: { answer: 'Coruscant', check: 'false' },
    },
    {
        question: 'While fighting his own father in the Cloud City, which hand does Luke Skywalker lose?',
        1: { answer: 'Right', check: 'true' },
        2: { answer: 'Left', check: 'false' },
        3: { answer: 'Both', check: 'false' },
        4: { answer: 'Neither', check: 'false' },
    },
    {
        question: 'Who defeats Finn in his very first lightsaber duel?',
        1: { answer: 'Darth Maul', check: 'false' },
        2: { answer: 'Darth Vader', check: 'false' },
        3: { answer: 'Kerok Vet', check: 'false' },
        4: { answer: 'Kylo Ren', check: 'true' },
    },
    {
        question: 'What is Chewbacca’s weapon of choice?',
        1: { answer: 'Blaster rifle', check: 'false' },
        2: { answer: 'Lightsaber', check: 'false' },
        3: { answer: 'Metal club', check: 'false' },
        4: { answer: 'Bowcaster', check: 'true' },
    },
    {
        question: 'What are the creatures, living on Endor, that helped the Rebel’s to defeat the second Death Star?',
        1: { answer: 'Ewoks', check: 'true' },
        2: { answer: 'Wookies', check: 'false' },
        3: { answer: 'Nerf Herders', check: 'false' },
        4: { answer: 'Jawas', check: 'false' },
    },
    {
        question: 'What nickname does Han Solo call Luke Skywalker that drives him crazy?',
        1: { answer: 'Buckaroo', check: 'false' },
        2: { answer: 'Skydancer', check: 'false' },
        3: { answer: 'Kid', check: 'true' },
        4: { answer: 'Lukie', check: 'false' },
    },
    {
        question: 'Who delivers the final blow that destroys the second Death Star?',
        1: { answer: 'Han Solo with an X-Wing', check: 'false' },
        2: { answer: 'Jar Jar Binks with a Y-Wing', check: 'false' },
        3: { answer: 'Luke Skywalker with a Speeder', check: 'false' },
        4: { answer: 'Lando Calrissian with the Millennium Falcon', check: 'true' },
    },
    {
        question: 'Alright, who blew up the first Death Star, and with what weapon?',
        1: { answer: 'Luke Skywalker with his Lightsaber', check: 'false' },
        2: { answer: 'Luke Skywalker with an X-Wing', check: 'true' },
        3: { answer: 'Princess Leia with an X-Wing', check: 'false' },
        4: { answer: 'Princess Leia with a thermal detonator', check: 'false' },
    },
    {
        question: 'What does Han Solo have to say about the Force in A New Hope?',
        1: { answer: '“Listen Kid, I can use the force like any of you, I just don’t want to.”', check: 'false' },
        2: { answer: '"Hokey religions and ancient weapons are no match for a good blaster at your side, kid."', check: 'true' },
        3: { answer: '“I wouldn’t be caught dead with those midichlorians in my blood!”', check: 'false' },
        4: { answer: '“You can never be too safe. The force is a powerful ally”', check: 'false' },
    },
    {
        question: 'What race does the comical Jar Jar Binks belong to?',
        1: { answer: 'The Naboo', check: 'false' },
        2: { answer: 'The Wookies', check: 'false' },
        3: { answer: 'The Hutt', check: 'false' },
        4: { answer: 'The Gungan', check: 'true' },
    },
    {
        question: 'Which character says the famous quote, "A Jedi Knight? Jeez, Im out of it for a little while, everyone gets delusions of grandeur!" in Episode VI: Return of the Jedi?',
        1: { answer: 'Han Solo', check: 'true' },
        2: { answer: 'Luke Skywalker', check: 'false' },
        3: { answer: 'Chewie', check: 'false' },
        4: { answer: 'Lando Calrissian', check: 'false' },
    },
    {
        question: 'What colors is the lovable droid BB-8?',
        1: { answer: 'White and blue', check: 'false' },
        2: { answer: 'White and orange', check: 'true' },
        3: { answer: 'White and red', check: 'false' },
        4: { answer: 'Black and green', check: 'false' },
    },
    {
        question: 'And what about R2D2, what colors cover this handsome little devil?',
        1: { answer: 'Silver and black', check: 'false' },
        2: { answer: 'Green and yellow', check: 'false' },
        3: { answer: 'White and orange', check: 'false' },
        4: { answer: 'White and blue', check: 'true' },
    },
    {
        question: 'What planet is Rey living on when BB-8 finds her?',
        1: { answer: 'Jakku', check: 'true' },
        2: { answer: 'Hoth', check: 'false' },
        3: { answer: 'Tatooine', check: 'false' },
        4: { answer: 'Endor', check: 'false' },
    },
    {
        question: 'What color is the first lightsaber Rey uses?',
        1: { answer: 'Blue', check: 'true' },
        2: { answer: 'Red', check: 'false' },
        3: { answer: 'Green', check: 'false' },
        4: { answer: 'Purple', check: 'false' },
    },
    {
        question: 'What is Princess Leia’s famous line, recorded by R2D2 for her Jedi friend?',
        1: { answer: '"Help me, Obi-Wan Kenobi. You`re my only hope"', check: 'true' },
        2: { answer: '“This bucket of bolts`s never gonna get us past that blockade.”', check: 'false' },
        3: { answer: '“Han, we need you.”', check: 'false' },
        4: { answer: '“Captain, being held by you isn`t quite enough to get me excited.”', check: 'false' },
    },
    {
        question: 'How many children does Darth Vader have?',
        1: { answer: 2, check: 'true' },
        2: { answer: 3, check: 'false' },
        3: { answer: 5, check: 'false' },
        4: { answer: 6, check: 'false' },
    },
    {
        question: 'With what famous Sci-fi film does the original Star Wars trilogy share a production crew?',
        1: { answer: 'Space Quest', check: 'false' },
        2: { answer: 'Star Trek', check: 'false' },
        3: { answer: 'Space Odyssey 2001', check: 'true' },
        4: { answer: 'Battle Star Galactica', check: 'false' },
    },
]